'use strict';
const D=window.WireData,E=window.WireEngine,app=document.getElementById('app');
const modes={basic:'基礎練習',guided:'手順つき練習',challenge:'6問チャレンジ',random:'ランダムチャレンジ',review:'間違えた問題の復習'};
let state;try{state=E.restore(localStorage.getItem(E.KEY));}catch{state=E.fresh();notice();}
let screen=state.session?'session':'home';
function notice(){document.getElementById('notice').hidden=false;}
function save(){try{localStorage.setItem(E.KEY,JSON.stringify(state));}catch{notice();}}
const esc=text=>String(text).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const lines=text=>esc(text).replace(/\n/g,'<br>');
const button=(act,text,cls='',attrs='')=>`<button type="button" data-act="${act}" class="${cls}" ${attrs}>${esc(text)}</button>`;
function home(){const active=state.session&&state.session.phase!=='result';return `<section class="welcome"><p class="eyebrow">WIRE & CURRENT</p><h1 tabindex="-1">表を読む。式をつなぐ。<br>6問を、自分の力で。</h1><p>単線の直径 mm と、より線の断面積 mm²。<br>必要な電流を流せる電線を選ぶ練習です。</p></section>${active?`<div class="resume"><span>${modes[state.session.mode]} ${state.session.index+1}/${state.session.order.length} を中断中</span>${button('resume','続きから →','primary')}</div>`:''}<section class="modes" aria-label="練習モード"><article><span class="number">01</span><h2>基礎練習</h2><p>単位・許容電流・係数を読む。<br>必要な表をいつでも確認。</p><small>アプリ独自の基礎練習 · 6問</small>${button('start-basic','表を見ながら練習 →','primary')}</article><article><span class="number">02</span><h2>手順つき練習</h2><p>教材6問を、一段階ずつ。<br>選んだ数値が式につながります。</p><small>表あり · 1問ずつ手順を確認</small>${button('start-guided','手順を確かめる →','primary')}</article><article><span class="number">03</span><h2>6問チャレンジ</h2><p>教材の問題・選択肢で挑戦。<br>迷ったときは表やヒントを開けます。</p><small>最初は表なし · 固定順</small>${button('start-challenge','6問に挑戦 →','primary')}</article></section><section class="record"><div><h2>手助けなしの連続パーフェクト</h2><p>固定6問で、初回回答がすべて正解なら1回。<br>2回連続でランダムモードを解放します。</p></div><strong>${state.streak}<small> / 2</small></strong>${button('start-random',state.unlocked?'ランダムモードで練習 →':'ランダムモード・未解放','',state.unlocked?'':'disabled')}<p class="small">${state.unlocked?'✓ 解放済み。これからも自由に使えます。':'表・ヒントを使った周や、再挑戦した周は連続回数を0に戻します。'}</p></section><div class="settings">${button('sound',`音 ${state.sound?'ON':'OFF'}`,'quiet',`aria-pressed="${state.sound}"`)}${button('reset','学習記録をリセット','quiet')}</div><p class="small">完了した周：${Object.entries(state.completed).map(([k,v])=>`${modes[k]} ${v}`).join(' ／ ')}</p>`;}
function table(key,title,heading,rows,ref){return `<section class="reference"><h3>${title}</h3><table><thead><tr>${heading.map(t=>`<th scope="col">${t}</th>`).join('')}</tr></thead><tbody>${rows.map((row,i)=>`<tr class="${ref&&ref[0]===key&&ref[1]===i?'highlight':''}">${row.map((v,j)=>j===0?`<th scope="row">${ref&&ref[0]===key&&ref[1]===i?'→ ':''}${esc(v)}</th>`:`<td>${esc(v)}</td>`).join('')}</tr>`).join('')}</tbody></table></section>`;}
function tables(ref){return `<aside class="tables" aria-label="教材の参照表"><h2>表を確認</h2><p class="small">周囲温度30℃。印刷された数値のみを掲載しています。</p>${table('single','表1⑴ 絶縁電線：単線',['直径［mm］','許容電流［A］'],D.single,ref)}${table('stranded','表1⑴ 絶縁電線：より線',['断面積［mm²］','許容電流［A］'],D.stranded,ref)}${table('factors','表2 電流減少係数',['同一管内の電線数','係数'],D.factors,ref)}<p class="small">ケーブルを扱う問1は、問題文で指定された係数を使います。</p><details><summary>別表：コードの許容電流</summary><p class="small">教材6問で使う絶縁電線の表とは別です。</p>${table('cord','表1⑵ コード',['断面積［mm²］','素線数 / 直径［本 / mm］','許容電流［A］'],D.cord,null)}</details></aside>`;}
function quiz(){const s=state.session,q=E.item(s),p=E.prompt(s),r=s.results[q.id],guided=E.learningMode(s)==='guided';const ref=s.highlight?p.ref||q.ref:null;
return `<nav>${button('home','← ホーム','quiet')}<span>${modes[s.mode]}</span><b>${s.index+1} / ${s.order.length}</b></nav><progress value="${s.index}" max="${s.order.length}" aria-label="完了した問題数"></progress><div class="learning ${s.table?'with-table':''}"><section class="question panel"><p class="eyebrow">${q.id} ${E.learningMode(s)==='basic'?'アプリ独自の基礎練習':'教材41ページ'}${guided?` · ステップ ${s.step+1}/${q.steps.length}`:''}</p><h1 tabindex="-1">${lines(q.text)}</h1>${guided?`<p class="condition">${esc(q.label)}</p>${s.step?`<ol class="trail" aria-label="正解済みの手順">${q.steps.slice(0,s.step).map(t=>`<li><span>✓ ${esc(t.text)}</span><b>${esc(t.options[t.answer])}</b></li>`).join('')}</ol>`:''}${s.step===3&&q.id!=='Q6'?`<p class="equation">${esc(q.steps[2].options[0])} ＝ ${['24.5','15.12','34.3','22.05','25.9'][Number(q.id.slice(1))-1]} A</p>`:''}<h2>${esc(p.text)}</h2>`:''}${!['basic','guided'].includes(E.learningMode(s))?`<div class="help">${button('table',s.table?'表を閉じる':'表を見る','',`aria-expanded="${s.table}"`)}${button('hint','ヒントを見る')}</div><p class="small">${r?.help?'手助けありとして記録しています。':'表・ヒントを開くと「手助けあり」になります。'}</p>`:''}<div class="answers">${p.options.map((opt,i)=>button(`answer-${i}`,`${s.selected===i?'選択：':''}${opt}`,'',s.phase==='answer'?'':'disabled')).join('')}</div>${s.hint?`<aside class="hint" role="status"><b>確認ポイント</b><p>${lines(p.hint||q.explanation)}</p></aside>`:''}${s.phase!=='answer'?`<div class="feedback ${s.phase}" tabindex="-1" role="status"><h2>${s.phase==='correct'?'✓ 正解！':'ここを確認して、もう一度'}</h2>${s.phase==='correct'?`<p>${lines(guided&&s.step<q.steps.length-1?p.options[p.answer]:q.explanation)}</p>`:''}${button('next',s.phase==='wrong'?'もう一度':guided&&s.step<q.steps.length-1?'次の手順 →':'次へ →','primary')}</div>`:''}</section>${s.table?tables(ref):''}</div>`;}
function result(){const s=state.session,rs=Object.values(s.results),retry=rs.filter(r=>r.wrong).length,help=rs.filter(r=>r.help).length;
return `<section class="panel result"><p class="eyebrow">${modes[s.mode]} · 完了</p><h1 tabindex="-1">${retry===0?'全問、最初から正解！':'最後まで、やりきりました。'}</h1><div class="scores"><div><strong>${rs.length-retry}</strong><span>最初から正解</span></div><div><strong>${retry}</strong><span>再挑戦で正解</span></div></div><p>手助けあり：${help}問</p><p>固定チャレンジの連続パーフェクト：<b>${state.streak} / 2</b></p>${s.justUnlocked?'<p class="unlock">✓ ランダムモードが解放されました！</p>':''}${s.mode==='challenge'&&help?'<p>表やヒントで確認できました。次は手助けなしで挑戦してみよう。</p>':''}${retry?button('review','間違えた問題だけ、もう一度','primary'):''}${button('again','もう1周')}${button('home','ホームへ')}${retry===0?`<div class="confetti" aria-hidden="true">${Array.from({length:16},(_,i)=>`<i style="--i:${i}"></i>`).join('')}</div>`:''}</section>`;}
function render(focus=true){app.innerHTML=screen==='home'?home():state.session.phase==='result'?result():quiz();if(focus){const target=app.querySelector('.feedback')||app.querySelector('h1');target?.focus();target?.scrollIntoView({block:'nearest'});}}
let audio;
function sound(){if(!state.sound)return;try{const Audio=window.AudioContext||window.webkitAudioContext;if(!Audio)return;audio ||=new Audio();const play=()=>{const o=audio.createOscillator(),g=audio.createGain(),t=audio.currentTime;o.connect(g);g.connect(audio.destination);o.frequency.setValueAtTime(660,t);o.frequency.setValueAtTime(880,t+.08);g.gain.setValueAtTime(.06,t);g.gain.exponentialRampToValueAtTime(.001,t+.2);o.start(t);o.stop(t+.21);};if(audio.state==='suspended')audio.resume().then(play).catch(()=>{});else play();}catch{}}
app.addEventListener('click',ev=>{const b=ev.target.closest('button[data-act]');if(!b||b.disabled)return;const a=b.dataset.act;
if(a==='reset'){if(!confirm('このアプリの学習記録と音設定をリセットしますか？'))return;try{localStorage.removeItem(E.KEY);}catch{notice();}state=E.fresh();screen='home';render();return;}
if(a==='sound'){state.sound=!state.sound;save();b.textContent=`音 ${state.sound?'ON':'OFF'}`;b.setAttribute('aria-pressed',state.sound);return;}
if(a==='home')screen='home';
else if(a==='resume')screen='session';
else if(a.startsWith('start-')){if(state.session&&state.session.phase!=='result'&&!confirm('進行中の周を終了して、新しい練習を始めますか？'))return;if(!E.start(state,a.slice(6)))return;screen='session';}
else if(a.startsWith('answer-')){if(!E.answer(state,Number(a.slice(7))))return;if(state.session.phase==='correct')sound();}
else if(a==='next'){if(!E.advance(state))return;}
else if(a==='table'){if(state.session.table)state.session.table=false;else E.help(state,'table');save();render(false);app.querySelector('[data-act="table"]')?.focus();return;}
else if(a==='hint')E.help(state,'hint');
else if(a==='review'){const old=state.session;const ids=old.order.filter(id=>old.results[id].wrong);E.start(state,'review',ids,E.learningMode(old));}
else if(a==='again'){const old=state.session;E.start(state,old.mode,old.mode==='review'?old.order:undefined,E.learningMode(old));}
save();render();});
render(false);
